name: Automatic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run python
        run: python3 benchmark_fake.py
      - name: Zip the files
        run: zip target.zip Slope.txt ParamPath.txt Rosenbrock function with hyper-optimizationarg_list.txt Rosenbrock function with hyper-optimizationlabel_list.txt Rosenbrock function with hyper-optimizationvalue_list.txt Rosenbrock function without hyper-optimizationarg_list.txt Rosenbrock function without hyper-optimizationlabel_list.txt Rosenbrock function without hyper-optimizationvalue_list.txt
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          run: |
           echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
           echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this release:
            - Added feature A
            - Fixed issue B
            - Improved performance
            
      - name: Upload Release Assets
        id: upload_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target.zip
          asset_name: target.zip
          asset_content_type: application/zip
